version: "3"
volumes:
  db:
  media:
services:

  # PROXY
  proxy:
    image: jwilder/nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports: 
      - 80:80

  # PROFESSIONAL SITE
  professional-site:
    image: jteppinette/professional-site
    environment:
      - VIRTUAL_HOST=localhost,home.localhost

  # DB
  db:
    image: mysql
    env_file: .env
    environment:
      - MYSQL_USER=db
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - db:/var/lib/mysql

  # GO JSON API SEED
  go-json-api-seed:
    image: jteppinette/go-json-api-seed
    environment:
      - VIRTUAL_HOST=go-json-api-seed.localhost

  # AMP
  amp:
    image: jteppinette/amp
    env_file: .env
    environment:
      - VIRTUAL_HOST=amp.localhost
      - APP_URL=amp.localhost
      - DB_NAME=amp
      - DB_PORT=3306
    links:
      - db
    volumes:
      - media:/app/media

  # DJANGO API SEED
  django-api-seed:
    image: jteppinette/django-api-seed
    env_file: .env
    environment:
      - VIRTUAL_HOST=django-api-seed.localhost
      - DB_NAME=djangoapiseed
      - DB_PORT=3306
    links:
      - db

  angular-seed:
    image: jteppinette/angular-seed
    environment:
      - VIRTUAL_HOST=angular-seed.localhost
    links:
      - django-api-seed:upstream

  # RISK MANAGED
  risk-managed:
    image: jteppinette/risk-managed
    env_file: .env
    environment:
      - VIRTUAL_HOST=risk-managed.localhost
      - DB_NAME=riskmanaged
      - DB_PORT=3306
    links:
      - db
    volumes:
      - media:/app/media

  # WATER DRAGON
  water-dragon-api:
    image: jteppinette/water-dragon-api
    env_file: .env
    environment:
      - VIRTUAL_HOST=api.water-dragon.localhost
      - DB_NAME=waterdragon
      - DB_PORT=3306
    links:
      - db
    volumes:
      - media:/app/media

  # PERAGRIN
  peragrin-client:
    image: jteppinette/peragrin-client
    environment:
      - VIRTUAL_HOST=app.peragrin.localhost
    links:
      - peragrin-api:upstream

  peragrin-api:
    image: jteppinette/peragrin-api
    env_file: .env
    environment:
      - VIRTUAL_HOST=api.peragrin.localhost
      - DB_NAME=peragrin
      - DB_PORT=3306
    links:
      - db
