defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]
email = "josheppinette@icloud.com"
storage = "acme.json"
entryPoint = "https"
onDemand = false

[[acme.domains]]
  main = "{{ domain }}"
  sans = [
    "go-json-api-seed.{{ domain }}",
    "amp.{{ domain }}",
    "django-api-seed.{{ domain }}",
    "angular-seed.{{ domain }}",
    "risk-managed.{{ domain }}",
    "api.water-dragon.{{ domain }}",
    "minio.{{ domain }}"
  ]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "{{ domain }}"
watch = true
swarmmode = true
exposedbydefault = false
